### ISSUE TITLE
[bug] enigma server gives NoClassDefFoundError when run

### ISSUE THREAD

**Issue by Miningpro362** [QuiltMC/enigma#116]
iirc since the time of duvetmc's chaosmappings being in active development, there has been an issue that would occur when trying to run the enigma server where it spits out ```Error: Unable to initialize main class cuchaz.enigma.network.DedicatedEnigmaServer
Caused by: java.lang.NoClassDefFoundError: cuchaz/enigma/translation/mapping/serde/MappingParseException``` when run. built from source very recently (as in just minutes ago).

**Comment by ix0rai** [comment]
thank you for the report!
can you give reproduction steps (how exactly you're running it)?

**Comment by Miningpro362** [comment]
after building we ran `java -jar enigma-server/build/libs/enigma-server-1.8.6+local` from the root dir of the project and got the error (using openjdk 17.0.7 on arch)

**Comment by ByMartrixx** [comment]
I think this is because the server jar isn't a shadow one and therefore doesn't include any of its dependencies

**Comment by ix0rai** [comment]
@Miningpro362 with the latest commit you can simply use the `-all` jar generated by shadow!

**Comment by Miningpro362** [comment]
thanks, glad to have this resolved

**Comment by Miningpro362** [comment]
oop, new issue
```Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [jar, mappings]
at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:435)
at joptsimple.OptionParser.parse(OptionParser.java:409)
at cuchaz.enigma.network.DedicatedEnigmaServer.main(DedicatedEnigmaServer.java:95)```

**Comment by ix0rai** [comment]
well that's your issue :p
you have to provide `-mappings and -jar` to start a server

**Comment by Miningpro362** [comment]
oh, i'm stupid.

**Comment by Miningpro362** [comment]
there we go, tysm
