### ISSUE TITLE
mapping stats graph doesn't properly display when a filter is set

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/enigma#134]
reproduction steps:
1. open any project
2. press file -> mapping stats
3. check a couple boxes
4. type something in the "filter" input
5. generate graph and see issue: a blue circle is displayed, with "NaN" as a tooltip when hovered

**Comment by ByMartrixx** [comment]
I remember a similar issue that was just because the  stats dialog expected "net.minecraft" instead of "net/minecraft"

**Comment by ix0rai** [comment]
am I stupid? stay tuned to find out!

**Comment by ix0rai** [comment]
turns out I'm stupid!
