### ISSUE TITLE
No indentation since 2.0

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/enigma#180]
Since the 2.0 update, there's been no indentation except for the outermost class. 
![java_u0nMEx2csc](https://github.com/QuiltMC/enigma/assets/618276/db587429-3f25-415e-bd37-e3e2ac273b8e)

**Comment by ix0rai** [comment]
just adding info that we discussed in the discord here: this regression was introduced with #167

**Comment by ix0rai** [comment]
@poopooracoocoo I take your thumbsup as an indication that you can reproduce this issue. could you test on the latest commit using `gradlew completeTestGui` and send me your system information?

**Comment by ix0rai** [comment]
adding info from Discord:
- when not using the syntaxpain java syntax kit, this issue is not present
- this issue appears only on VF, not CFR or Procyon

**Comment by ix0rai** [comment]
the first commit where this issue is observable is https://github.com/QuiltMC/enigma/commit/ffc84d99b0c72370c05d02635548543467fe97dd.  commits before that one in #167 do not boot so we don't know exactly which commit introduced the issue

**Comment by ix0rai** [comment]
i win
