### ISSUE TITLE
validate duplicate variable names for lambdas

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/enigma#188]
lambda names can conflict with other variables within their scope. I'm actually not sure they're validated for uniqueness at all

**Comment by ix0rai** [comment]
once this is implemented, it should probably be implemented into `dropInvalidMappings`, with the smallest-scoped name being dropped

**Comment by IotaBread** [comment]
This is quite hard to do since local variables don't have a name by default if their method doesn't have an LVT; missing names are filled by the decompiler, so it's up to it what names the variables take. Checking conflicts between known names is easier though

**Comment by ix0rai** [comment]
that's what I meant, checking enclosing parameters and other lambdas
