### ISSUE TITLE
Hang on "Processing: progress.jar.indexing.process.lambdas"

### ISSUE THREAD

**Issue by Decencies** [QuiltMC/enigma#206]
Input:
[combined.zip](https://github.com/user-attachments/files/15526447/combined.zip)

Enigma does not log anything useful in console and hangs until closed.

**Comment by ix0rai** [comment]
this seems to open fine for me with #197, let me know if it works for you!
![Screenshot_20240602_210556](https://github.com/QuiltMC/enigma/assets/66223394/c56d29e4-fe4a-49e8-aa62-fcf0ca8dd2a3)
