### ISSUE TITLE
Some method parameters are incorrectly marked as mappable

### ISSUE THREAD

**Issue by PiTheGuy** [QuiltMC/enigma#207]
Consider the following class:
![image](https://github.com/QuiltMC/enigma/assets/55959311/328949c7-300c-43a1-bfb3-2ca43c639620)
This shows as completely unmapped (0/4) on the side panel and reports 4 unmapped parameters in the stats tree,

After some investigation, I found the record's `<init>` and `equals` methods are considered unmapped and count towards the total, despite being unmappable and completely hidden from the user.

This is the same issue as https://github.com/FabricMC/Enigma/issues/502 except it no longer affects enums.

**Comment by ix0rai** [comment]
I've started looking into this, and I'm still not sure why it happens. Next I need to set up a minimal reproduction case.

**Comment by ix0rai** [comment]
little update I'm trying to fix up records in general with this, as they're quite broken. fix will be delayed a while
