### ISSUE TITLE
Filtering by top-level packages is broken

### ISSUE THREAD

**Issue by CrypticVerse** [QuiltMC/enigma#220]
While using Enigma, I wanted to filter by package, to see what needed mapped. When I clicked the filter button, even if the package is 0% mapped, the filter always shows 100%.
Also, when using net/minecraft instead of net.minecraft (`/` instead of `.`), the mappings filter correctly, but I run into the issue described in #134. (Blue circle with NaN).
Normal (Expected):
![expected](https://github.com/user-attachments/assets/cffb50e1-e3a8-4c1e-9384-1506003f9f53)
Bug:
![bug](https://github.com/user-attachments/assets/e0121849-c8a9-4335-84c1-5cd454e12861)

Steps to reproduce:
1. Clone QM and run `./gradlew mappings`
2. Click file in swing, and click `Mapping Stats`
3. Type in a package that is **NOT** fully mapped yet in the `Top-Level Package` box.
4. Click filter and see that every time it shows `100.00%`, even when I can see that the package (not including lambdas) is not fully mapped.

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
