### ISSUE TITLE
Adding javadoc to method override param is allowed but flawed

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/enigma#225]
Working on a QMap PR based on https://github.com/QuiltMC/quilt-mappings/commit/5f958526ccfcb3e3b8c9a3d31ea31fdcbd2ce487

I can edit the javadoc of the param of `net.minecraft.world.tick.ChunkTickScheduler#getAllTicks` (`m_khwqakbu`), which is an override of `net.minecraft.world.tick.SerializableTickScheduler#getAllTicks`.

In the editor it looks like this, with null for the param name:
![java_HH9q6JG04r](https://github.com/user-attachments/assets/53d764eb-89d0-4c95-95c6-3516ae3db943)

The mapping file looks like this:
```
METHOD m_khwqakbu (J)Ljava/util/List;
	ARG 1
		COMMENT used to convert from {@link net.minecraft.world.tick.OrderedTick#triggerTick() OrderedTick.triggerTick}
		COMMENT to {@link net.minecraft.world.tick.Tick#delay() Tick.delay}
```

And in fakeSource it looks like this:
```java
   /**
    * Mapping not found
    */
   @Override
   public List<Tick<T>> getAllTicks(long time) {
```

Adding the comment to the base method's param works fine.

**Comment by ix0rai** [comment]
can confirm. will create a test for this and get it fixed!
