### ISSUE TITLE
Upward propagation doesn't update stats

### ISSUE THREAD

**Issue by PiTheGuy** [QuiltMC/enigma#230]
When you map something from a subclass, it automatically propagates to the superclass, but the superclass's stats don't update, causing the superclass to show a yellow or red icon despite being fully mapped. 

Considering the following example:
```java
public interface SomeInterface {
    void someMethod(SomeType t);
}

public class SomeClass implements SomeInterface {
    public void someMethod(SomeType t) {
        
    }
}
```
if you were to map the `t` parameter from `SomeClass`, it would propagate to `SomeInterface` as expected, but the stats for `SomeInterface` wouldn't update. `SomeInterface` would still show a red icon (0/1) until you manually mapped something in it to force a stats update.

**Comment by ix0rai** [comment]
right, i misread. will get this fixed!
