### ISSUE TITLE
[bug] cut off elements in right button bar

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/enigma#27]
as visible in this image, the top border of the buttons in the right selector is cut off. this is due to some sort of error in `RightAngleLayerUI`, which is used to rotate the buttons clockwise to save space.
![image](https://user-images.githubusercontent.com/66223394/211951400-ffa11d6a-4355-4450-95c1-c805c7cb3f9e.png)

@2xsaiko I asked you on discord about this issue but didn't get a response, would you mind looking into it?

**Comment by 2xsaiko** [comment]
I know about this, but I have no idea what causes it. It is probably just an off-by-one error where the button is drawn a pixel too far to the right or something.

**Comment by ix0rai** [comment]
that was my thought, I'll look into making a workaround myself
