### ISSUE TITLE
Anti-aliased text

### ISSUE THREAD

**Issue by LambdAurora** [QuiltMC/enigma#3]
It's already possible to get it with command line arguments but it would be nicer if it was built-in.

Only those properties are required:
```java
        // Make text anti-aliased.
        System.setProperty("awt.useSystemAAFontSettings", "on");
        System.setProperty("swing.aatext", "true");
```

**Comment by 2xsaiko** [comment]
Going to set the values only if they're not already set explicitly (if you want to disable those options using -D flags, you should still be able to)
