### ISSUE TITLE
[feature request] indication of file mapping status

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/enigma#53]
idea:
in class tree dockers, classes should have a little icon next to them: either a red x, a yellow circle, or a green check. this indicates how mapped the file is: x for not mapped at all, circle for some mappings but not 100%, green for 100%. this will make it much easier to tell what needs work at-a-glance.

notes:
sort of a simpler equivalent to https://github.com/FabricMC/Enigma/pull/482

**Comment by OroArmor** [comment]
I think hovering over a class should have a popup for % mapped which looks at all names, and then pressing shift would have a larger breakdown based on fields, methods, parameters and classes
