### ISSUE TITLE
[bug] warning when renaming a method with a seperate method signature to the same name of an existing method

### ISSUE THREAD

**Issue by tas-pro** [QuiltMC/enigma#55]
If I try to rename a method to match the name of another method in the same class, it will give me a warning expectantly. However, this warning will appear despite the method signatures being different.

![image](https://user-images.githubusercontent.com/124226059/219287917-afbf72a7-8804-4564-86d6-c579a4a81f7f.png)

**Comment by ix0rai** [comment]
I'm not sure I entirely understand your description.
the shadowing warning is intended to prevent something like this, where the field `name` is duplicated in `E`, which means you'd have to use `D.this.name` to access the `name` field of `D` when running code from `E`. I couldn't seem to throw the warning in my testing though, so a reproduction case would be great.
```java
	public class D {
		public int name;
		public String a;

		public void b() {
		}

		public class D.E {
			public int name;

			public void b() {
			}
		}
	}
```

**Comment by ix0rai** [comment]
oh never mind, sorry
I was able to reproduce. will look into this, and also look into why I get three warnings at once when I see it.
