### ISSUE TITLE
[bug] Renaming an entry resets the class information panel

### ISSUE THREAD

**Issue by Decencies** [QuiltMC/enigma#75]
When other users connected to the same server and renames an entry, the input field, if currently active, loses focus and resets.

Same as [#324](https://github.com/FabricMC/Enigma/issues/324) in Fabric's Fork.

Replication:
1. Start enigma server
2. Login in on 2 instances of enigma (preferably from a different computer to see the bug in practice)
3. Start renaming an arbitrary entry on one of the clients
4. While still renaming the entry, on the other client, commit a mapping to another arbitrary entry

Tested versions: latest

**Comment by ix0rai** [comment]
struggling to reproduce.

my steps:
1. start server and connect two clients, different computers
2. start renaming an entry on the first client
3. start renaming the same entry on the second
4. commit the mapping from the first client
5. bug does not appear, no changes have been lost and the second client can still commit their in-progress mapping

**Comment by sschr15** [comment]
What's the version reported under Help -> About? This bug should have been fixed in one of the more recent versions

**Comment by Decencies** [comment]
My apologies, I appear to be using a slightly outdated version of the Enigma client. I will test again with the latest version and report back!

(p.s. I thought this issue was actually an issue in swing itself since I can't find any code which "refreshes" the information panel after receiving a committed mapping, or maybe I'm not looking hard enough)

**Comment by ix0rai** [comment]
it was fixed in `1.5.2` with pr #33, just for a little more info!
