### ISSUE TITLE
[feature request] automatically rename packages in obf view

### ISSUE THREAD

**Issue by Decencies** [QuiltMC/enigma#94]
When a (de-)obfuscated package is renamed, classes under the same package should be changed in the obfuscated view.

Obviously not all input binaries will have a package structure, but for those which do, it is a massive time saver to have it mapped automatically by Enigma.

**Comment by ix0rai** [comment]
agreeing with oro here, this would make refactoring impossible
I think the best solution is to add this to a right-click menu in the class tree

**Comment by Decencies** [comment]
> agreeing with oro here, this would make refactoring impossible
> I think the best solution is to add this to a right-click menu in the class tree

but if for example i have a/b/c and rename it to com/domain/app, it should rename anything like a/b/c/d/... to com/domain/app/d/...

**Comment by ix0rai** [comment]
no, that wouldn't work
there's no way to distinguish renaming a package from moving a class without making them explicitly different actions, and I think the ideal way to do that would be to have package renaming in the class tree and class renaming in the identifier panel
